general {
    lock_cmd = pidof hyprlock || hyprlock   # don't spawn multiple hyprlock
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # turn screen on after wake
    ignore_dbus_inhibit = false
}

# 2.5 min — dim screen to 20%
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 20%
    on-resume  = brightnessctl -r
}

# 5 min — lock screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5.5 min — turn off displays
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# 30 min — suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
